services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass host user/group IDs for proper permissions
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    # Image and container names are set by the script via override
    volumes:
      # Main working directories
      - ./notebooks:/home/jovyan/notebooks
      - ./flowgraphs:/home/jovyan/flowgraphs
      - ./scripts:/home/jovyan/scripts
      - ./data:/home/jovyan/data
      
      # Optional: Mount project pyproject.toml for runtime template customization
      # This allows changing notebook templates without rebuilding
      # - ./pyproject.toml:/home/jovyan/notebooks/pyproject.toml:ro
      
    environment:
      # Locale settings
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      
      # Jupyter settings
      - JUPYTER_ENABLE_LAB=yes
      
      # Template system settings
      - JUPYTER_TEMPLATE_DEBUG=true
      
      # GNU Radio settings
      - GNURADIO_ENV=1
      
      # Optional: Variant marker for development/testing
      - VARIANT=${VARIANT:-default}
      
    ports:
      # Port is set dynamically by gnuradio-lab.sh
      - "${HOST_PORT:-8888}:8888"
      
    restart: unless-stopped
    
    # Resource limits (optional, adjust as needed)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 8G
    #     reservations:
    #       cpus: '2'
    #       memory: 4G
